<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'yii\\image\\' => array($vendorDir . '/yurkinx/yii2-image'),
    'cebe\\gravatar\\' => array($vendorDir . '/cebe/yii2-gravatar'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
    'Diff' => array($vendorDir . '/phpspec/php-diff/lib'),
    'Behat\\Gherkin' => array($vendorDir . '/behat/gherkin/src'),
    'BaconQrCode' => array($vendorDir . '/bacon/bacon-qr-code/src'),
);
